In [1]:
#6.3.1 comparing models
import  pandas as pd
hotel1=pd.read_csv("./hotel_final.csv")

In [2]:
del hotel1['Unnamed: 0']
del hotel1['Unnamed: 0.1']
del hotel1['Unnamed: 0.1.1']
hotel1.columns

Index(['hotel', 'arrival_date_year', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'market_segment', 'distribution_channel', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type',
       'days_in_waiting_list', 'customer_type', 'required_car_parking_spaces',
       'room_change', 'have_requests'],
      dtype='object')

In [3]:
###Train and Test Data
### set X(inputs) and Y(target)
!pip3 install sklearn
X=hotel1.drop("have_requests",axis=1)
y=hotel1["have_requests"]
### set the train and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.3, random_state=1)



Defaulting to user installation because normal site-packages is not writeable


In [4]:
### build the logistics model
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(X_train,y_train)
predictions=logmodel.predict(X_test)

/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [5]:
### output the accuracy 
from sklearn.metrics import classification_report
z=classification_report(y_test,predictions)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,predictions)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)
print(z)

              precision    recall  f1-score   support

           0       0.68      0.58      0.63     11015
           1       0.65      0.73      0.69     11535

    accuracy                           0.66     22550
   macro avg       0.66      0.66      0.66     22550
weighted avg       0.66      0.66      0.66     22550



In [6]:
### Train and test 
### Set X(input) and Y(target)
inputs=hotel1.drop('have_requests',axis='columns')
target=hotel1['have_requests']

In [7]:
### Set the train and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(inputs,target,test_size=0.3, random_state=1)

In [9]:
### Build the model by using decisiontree
import numpy as np
from sklearn import tree
# List of values to try for max_depth:
max_depth_range = list(range(1,5))
accurate=[]
for depth in max_depth_range:
    model= tree.DecisionTreeClassifier(max_depth = depth,random_state=1)
    Treemodel=model.fit(X_train,y_train)
    Treeprediction=model.predict(X_test)
    from sklearn.metrics import classification_report
    q=classification_report(y_test,Treeprediction)
    from sklearn.metrics import confusion_matrix
    o=confusion_matrix(y_test,Treeprediction)
    from sklearn.metrics import accuracy_score
    f=accuracy_score(y_test,Treeprediction)
    y_test_hat=model.predict(X_test)
    res=y_test==y_test_hat
    acc=np.mean(res)
    accurate.append(acc)
    print(o)
    print(q)
    print(f)


[[8092 2923]
 [3685 7850]]
              precision    recall  f1-score   support

           0       0.69      0.73      0.71     11015
           1       0.73      0.68      0.70     11535

    accuracy                           0.71     22550
   macro avg       0.71      0.71      0.71     22550
weighted avg       0.71      0.71      0.71     22550

0.7069623059866962
[[8092 2923]
 [3685 7850]]
              precision    recall  f1-score   support

           0       0.69      0.73      0.71     11015
           1       0.73      0.68      0.70     11535

    accuracy                           0.71     22550
   macro avg       0.71      0.71      0.71     22550
weighted avg       0.71      0.71      0.71     22550

0.7069623059866962
[[8120 2895]
 [3688 7847]]
              precision    recall  f1-score   support

           0       0.69      0.74      0.71     11015
           1       0.73      0.68      0.70     11535

    accuracy                           0.71     22550
   macro 